# This file sets some opinionated values for kube-score to use
# when parsing the chart
image:
  pullPolicy: Always

resources:
  requests:
    cpu: 1
    memory: 100Mi
  limits:
    cpu: 1
    memory: 100Mi