name: Lint and Test Charts

on: 
  push:
    paths:
      - 'deploy/helm/charts/**' 
      - '.github/**'            

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
          
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          config: .ci/ct-config.yaml
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        with:
          install_local_path_provisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: .ci/ct-config.yaml
