name: Publish helm chart

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**' 
      - '.github/**'     
      - 'deploy/manifests/**'    
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.1.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: sync gh-pages branch
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "gh-pages"
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        pr_allow_empty: false        